package.json

```
$ npm install
...
npm WARN babel-loader@6.2.5 requires a peer of babel-core@^6.0.0 but none was installed
$ npm start
...
Failed to compile.
Error in Cannot find module 'babel-core'
@ multi main
```
npm: 4.6.1
From [_SO_](https://stackoverflow.com/a/40805636):
> The reason behind this is that npm deprecated auto-installing of peerDependencies since npm@3, so required peer dependencies like babel-core and webpack must be listed explicitly in your package.json.

Add required peer dependency

---

src/layers.js
src/lib/leaflet.control.layers.configure/index.js
src/lib/leaflet.control.printPages/control.js
src/lib/leaflet.control.printPages/map-render.js
src/lib/leaflet.layer.rasterize/WestraPasses.js
src/lib/leaflet.layer.westraPasses/index.js

фикс для #43 
В качестве имен слоев использовал `options.code`, не уверен что это хорошая идея. Возможно лучше будет добавить каждому слою новую опцию? Например для OSM будет так:
`{code: 'O', scaleDependent: true, print: true, jnx: true, fileName: 'osm'}`

name exported PDF according to layer, zoom and page size

---

src/lib/leaflet.control.coordinates/coordinates.css
src/lib/leaflet.control.coordinates/formats.js
src/lib/leaflet.control.coordinates/index.js

Начал делать задачу #69, в итоге увлекся и почти полностью переделал контрол координат. Изменений получилось довольно много, вот их список:
1. Рефакторинг контрола: 
* убрал логику форматирования координат в `leaflet.control.coordinates/formats.js`, оставив в `leaflet.control.coordinates/index.js` только логику поведения контрола
* постарался консолидировать все что относится к форматам координат (строки типа "DMS" и "dd.ddd" и т.д.) в отдельные объекты
* использовал knockout observables для логики выбора текущего формата + мониторинга координат
2. Убрал контекстное меню с самого контрола, вместо этого добавил радио-кнопки выбора формата координат в окно где показываются сами координаты (что собственно и надо было сделать в #69).
3. Починил баг с паддингом отрицательных долгот нулями в …

Replace coordinates context menu with radio buttons

---

src/lib/leaflet.control.panoramas/lib/mapillary/index.js
webpack/webpack.config.js

* replace devtool option whith explicit definition of source map plugin.
This allows to configure it to excldue mapillary from processing
* require minimized version of mapillary package so that we can skip
minification during build
* specify config for TerserPlugin to skip minification of mapillary chunk
This drastically reduces build time (minification 20 sec -> 5 sec,
source maps generation 88 sec -> sec) but increases mapillary chunk
gzipped size by 13 Kb/3.7%  (351 Kb -> 364 Kb)

config: speedup build by skipping some stepps for mapillary package

---

src/App.js
src/config.js

В случае self-hosted использования хотелось бы иметь возможность поменять дефолтные местоположение и зум. Чтобы все это было в одном месте, предлагаю вынести это в config.js.

move defaultLocation and defaultZoom to config

---

src/lib/leaflet.layer.strava-heatmap/index.js
src/lib/notifications/index.js
src/lib/xhr-promise/index.js

automatically send request for cloudfront cookies when adding layer to
map and periodically every 24 hours.

strava heatmap: do automatic second stage login

---

src/leaflet-fixes.css
src/lib/leaflet.control.layers.configure/index.js
src/lib/leaflet.control.layers.configure/style.css

1. Limit display width in Layers control
2. Limit size accepted by input element.
Fixes #362

Limit layers names size

---

src/lib/leaflet.polyline-measure/index.js

Original logic:
* do not create any markers for very short tracks
New logic:
* add only ending marker for very short tracks
* skip the marker before the ending one if they are close to each other.
Fixes: #361

measured lines: change first/last marker placement logic

---

src/layers.js

Chrome now blocks all http images, no other workaround seen so far

layers: request http-only layers via proxy server

---

src/lib/leaflet.control.coordinates/formats.js

Number.prototype.toFixed rounds the value which can cause result like
60.00 minutes when the value is slightly less than integer value.

coordinates: fix rounding errors for DM and DMS formats

---

src/lib/leaflet.control.layers.configure/index.js
src/lib/leaflet.hashState/Leaflet.Control.Layers.js

Use generic map add/remove events instead of ones generated by layers
control. Layers can be added and removed when editing custom layers and
these do not produce layer control events.
Fixes #664.

layers: update  hash state when layers added/removed on map

---

src/lib/leaflet.control.track-list/track-list.js

Context menu passes original mouse event to callback functions. This
event was interpreted as "addElevations" parameter for "saveTrackAsFile"
function. Fixed by replacing currying with an arrow function without
parameters.
Fixes #821

tracks: do not request elevations when saving tracks

---

.github/workflows/main.yml

For unknown reason tests can not find firefox anymore, if it is no specifically installed

github actions: explicitly install firefox latest

---

src/layers.js

They stopped supporting m[1-4]. subdomains in ssl certificate

Layers: update URLs for mapy.cz

---

src/lib/leaflet.fixes/index.js

This fixes issue on Linux in Chrome and Firefox.

Fix map zooming 2 levels on each mouse wheel "tick"

---

test/test_track_load.js

Garmin Connect periodically changes order of points

tests: sort received points by name to avoid false failures

---

package.json

It has new import system which is not compatible with existing build script

build: do not update chalk to version 5.0.0

---

src/lib/leaflet.layer.geocaching-su/index.js

There was URL restructure at geocaching.su, while old links still work, let's use new up-to-date ones.

update geocaching.su cache URL

---

src/lib/leaflet.control.panoramas/lib/wikimedia/index.js

Thumbnail size was changed from 134 to 250 px, not sure if intentionally or accidentally, as iinfo.thumbwidth did not change. So now handling both variants.

panoramas: fix bug: wikimedia photos have low resolution

---

src/lib/leaflet.map.sidebars/style.css

In Chrome, when panoramas are above map, on small (mobile) screens, and more than 9 photos available, then scroll is not enabled for buttons and no right navigation arrow is visible.
The problem is that the middle layout column has minimum size of 470px. I do not know where this value comes from, and it is not so in Firefox.

panoramas - fix wikimedia photos window size.

---

src/lib/leaflet.control.track-list/track-list.css
src/lib/leaflet.control.track-list/track-list.js
src/lib/polygon-area/index.js
src/lib/polyline-selfintersects/index.js

Now tooltips for track segments display
- track name (not changed)
- segment ordinal number
- segment length
- area of polygon, surrounded by segment

tracks: add segment info to tooltips
