src/lib/leaflet.control.track-list/lib/geo_file_exporters.js

add time element inside of trkpt element (gpx compatibility to garmin connect)

---

src/lib/leaflet.control.track-list/lib/services/index.js
src/lib/leaflet.control.track-list/lib/services/osm.js
src/lib/leaflet.control.track-list/track-list.js

[Public GPS traces](https://www.openstreetmap.org/traces)
Примеры валидных ссылок:
- https://www.openstreetmap.org/user/sikmir/traces/2698308

[tracks] load tracks from osm url

---

.eslintrc
src/lib/notifications/style.css

fix alertify overflow #209

---

src/lib/leaflet.control.panoramas/index.js

this should fix shivering effect observed at some browser wibndow sizes.

panoramas: round container size

---

src/lib/elevations/index.js
src/lib/leaflet.control.elevation-profile/index.js
src/lib/leaflet.control.track-list/lib/geo_file_exporters.js
src/lib/leaflet.control.track-list/lib/meridian180.js
src/lib/leaflet.control.track-list/track-list.js

track list: add feature: save GPX with added elevations

---

src/lib/leaflet.control.track-list/track-list.js
src/lib/leaflet.fixes/fixWorldCopyJump.js

Fix gpx corssing 180

---

src/lib/leaflet.control.track-list/track-list.js

Change logic of suggested point names

---

src/lib/popup-window/index.js

display message when popup window is blocked 

---

src/lib/leaflet.control.track-list/lib/services/movescount.js

parsing tracks from movescount [fixed]

---

src/lib/leaflet.control.track-list/track-list.hash-state.js
src/lib/leaflet.control.track-list/track-list.js
src/lib/leaflet.control.track-list/track-list.localstorage.js

track list: Do not send track loading errors to Sentry. 

---

src/lib/leaflet.control.panoramas/lib/mapillary/mapillary-coverage-layer.js
src/lib/leaflet.control.panoramas/lib/wikimedia/coverage-layer.js
src/lib/leaflet.layer.wikimapia/index.js
src/lib/tiled-data-loader/index.js

tiled-data-loader: handle XHR errors. 

---

src/lib/leaflet.control.elevation-profile/index.js

Firefox and Chrome have different values in e.offsetX when event
originates at SVG element.
Relying on Chrome behavior breaks elevation graph selection in Firefox.
Fixed by using compatibility function instead.

elevation profile: use clientX instead of offsetX to get cursor position

---

package.json
src/lib/leaflet.control.search/providers/links.js
test/test_search_links.js
yarn.lock

search:  make google parser return 2 results for link with search results

---

src/lib/leaflet.control.track-list/track-list.js

tracks: Show waypoint name in context menu

---

src/lib/leaflet.control.printPages/control.css
src/lib/leaflet.control.printPages/control.js
src/lib/leaflet.control.printPages/form.html

print: add feature - position map to pages when clicking on pages number

---

src/lib/leaflet.hashState/Leaflet.Control.Layers.js

hashState for Layers control: fix loading state for base layers

---

src/lib/leaflet.control.track-list/track-list.css
src/lib/leaflet.control.track-list/track-list.js

#408 
Выложено на stage.nakarte.me

tracks: highlight track lines on hover. Fixes #408

---

src/App.js
src/lib/leaflet.control.locate/index.js

location: move forced and default location logic to caller

---

src/lib/leaflet.fixes/style.css

fix layers list on zooming out

---

src/lib/leaflet.control.track-list/track-list.js

prevent update markers on hidden track

---

src/lib/leaflet.control.panoramas/lib/wikimedia/style.css
src/lib/leaflet.map.sidebars/style.css

Do not mix flex with inline-block

Fix scrolling buttons container for wikimedia photos

---

src/lib/leaflet.layer.wikimapia/index.js
src/lib/leaflet.layer.wikimapia/wikimapia-loader.js
src/lib/leaflet.layer.wikimapia/wm-utils.js

[wikimapia] Update highlighted area under cursor after zoom

---

src/lib/leaflet.control.track-list/lib/services/wikiloc.js

Format of waypoints changed at wikiloc, updating prsing code

tracks: fix loading of Wikiloc waypoints

---

eslint_rules/base.js
src/config.js
src/lib/CORSProxy/index.js

Allow to bypass CORS proxy for particular urls.

---

src/layers.js

Use retina layer for OpenCycleMap and OSM Outdoors

---

src/layers.js

layers: Remove yandex tracks

---

src/App.js
src/config.js
src/lib/leaflet.control.coordinates/index.js
src/lib/leaflet.layer.elevation-display/index.js
src/lib/leaflet.layer.elevation-display/style.css

Coordinates: show elevation under cursor

---

src/lib/leaflet.control.track-list/lib/parsers/zip.js
src/lib/leaflet.control.track-list/track-list.css
src/lib/leaflet.control.track-list/track-list.js

- tracks: catch decompression error in zip 
- tracks: change icon to indicate tracks are beeen loaded when tracks controll is collapsed

Small zip improovmenets

---

src/lib/contextmenu/contextmenu.css

Multi-line context menu title

---

src/lib/leaflet.control.track-list/track-list.js

tracks: Menu item for copy coordinates of point

---

src/lib/leaflet.control.coordinates/coordinates.css
src/lib/leaflet.control.coordinates/index.js
src/lib/leaflet.layer.elevation-display/index.js

Coordinates control: enable to hide elevation at cursor
